include: package:flutter_lints/flutter.yaml

analyzer:
  exclude: 
    - lib/data/repositories/review_repository.dart
    - integration_test/*
    - lib/bloc/review_*.dart


linter:
  rules:
    prefer_relative_imports: true
    prefer_final_locals: true
    unnecessary_lambdas: true
    unnecessary_late: true
    unnecessary_parenthesis: true
    use_decorated_box: true
    use_named_constants: true

dart_code_metrics:
  rules:
    - avoid-unnecessary-type-casts
    - avoid-late-keyword
    - avoid-throw-in-catch-block
    - avoid-unused-parameters
    - newline-before-return
    - prefer-immediate-return
    - no-equal-then-else
    - no-boolean-literal-compare
    - prefer-async-await
    - avoid-wrapping-in-padding
    - prefer-extracting-callbacks
    - prefer-single-widget-per-file:
        ignore-private-widgets: true
  anti-patterns:
    - long-method:
      severity: warning
    - long-parameter-list:
      severity: warning
